# Generated by Django 2.0.13 on 2019-11-09 17:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombres', models.CharField(max_length=130)),
                ('Apellidos', models.CharField(max_length=130)),
                ('Lugar_nacimiento', models.CharField(max_length=130)),
                ('Fecha_Nacimiento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Cancion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=200)),
                ('Anio', models.CharField(max_length=200)),
                ('Duracion', models.CharField(max_length=200)),
                ('Genero', models.CharField(choices=[('Salsa', 'Salsa'), ('Bachata', 'Bachata'), ('Rock', 'Rock'), ('Merenge', 'Merenge'), ('Cumbia', 'Cumbia')], default='Salsa', max_length=10)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Colaboracion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Artista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.Artista')),
                ('Cancion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.Cancion')),
            ],
        ),
    ]
