# Generated by Django 2.0.13 on 2019-11-09 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artista',
            old_name='Apellidos',
            new_name='Nombre_artista',
        ),
        migrations.RemoveField(
            model_name='artista',
            name='Nombres',
        ),
    ]
